travis:
  secure:
    BINSTAR_TOKEN: QkYUwLthZNqH4RVj9T1M00bRs65YyAE9txibVmGm9HP06l6sV2TxwBVM2rMP7H2uBSn6uxLOgkN82jKTefQjCFORBzP4JB7xQAcK77OaUVIq5JEkgByRQ05omtf8fT/v06seHkPJmArLy7rv6GAYEvtmmVQL5dhnN7mcjP6SfuRYxz8KZlSkce8IMypAsxQmMQkUeGt070I2NlYuQXcBsnQC/CsMITrAyHwSRE5vOop4orXq3Uoup/+oa0GuVityTzoAiFicpNLyR7NNhG7tWTGwD7wkTWWMiCfKRtM5h9NuIQNCvnZZmbnAKKwL33wer8kQ0JsjpUViQ+uiNDuI5ojoc13D1p4prnphQCueFfw8NeOYp8f+5LN9dTjJl+rU4j4mIk9mxEHwnlZMG/uhD5sSL3SBZCkRMLTuH3TDy9rpKNUXfSLAtVm4ua8SRTOjgWyx2TUbfe69fVtFaXVxtpBsUD4YSWMmrNUn5PXj9JVvkPzbE2WK0LEIpyUyIQMG6X5FFEqDSOtd36WVBifWBEUdvaMI9zWrwhQaZ7qrDtJIK2FWHgVe06yELGN6/ljhgcQ5wivuZzKnlPm2dxQ1JKp70Lt+jIBspqjxRscW26qdu/Y04RQ2+JPMVuwJKwwkkMdETkJZxvMbDdoDrLFWVrLHNwuPqqBEqUkgC4zkvrI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
